### PR TITLE
fix: add simple reconnect backoff

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/mcollina/undici/issues/11

This is a rather simple backoff implementaiton. We could make it more advanced with more options. However, I think this should be good enough and adding more options will just confuse and make things more complicated.

### CODE REVIEW

**Comment by mcollina** [comment]
Could you add a test? would it be needed?

**Comment by ronag** [comment]
> Could you add a test? would it be needed?

I was thinking about this. I wouldn't mind adding one. But it would make the tests run slower.

**Comment by mcollina** [comment]
Should be ok anyway. You could also use sinonjs fake-timers to speed up time.

**Comment by ronag** [comment]
> You could also use sinonjs fake-timers to speed up time.

You mind if I merge this as is and make a note in the Test todo issue?

**Pull request merged**
