### PR TITLE
perf: optimize queue

### PR DESCRIPTION
**Pull request by ronag**
This replaces the fastq + inflight array with a single array + 2 indices.

Using the pattern moving things around is simply a matter of updating the indices to a buffer, with an amortized max limit on the buffer size.

undici benchmark

This PR: 2908.378ms
master: 6487.863ms

### CODE REVIEW

**Comment by ronag** [comment]
commits and messages need cleanup

**Comment by ronag** [comment]
Another optimization would be to re-use the requests objects in the queue.

**Comment by ronag** [comment]
@mcollina: Is it possible to reuse `AsyncResource` objects? i.e. re-using the `Request` objects?

**Comment by mcollina** [comment]
I would not reuse them.

**Pull request merged**
