### PR TITLE
feat: abort signal

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
@delvedor if you can pick up from here and add docs + tests that would be great and I will continue with the timeout stuff.

**Comment by ronag** [comment]
Right now it only works with `EventEmitter` might want to add support for https://www.npmjs.com/package/abort-controller as well.

**Comment by delvedor** [comment]
@ronag given that the project is small and we are just three persons, I think we can all create branches here instead of forking, which causes a lot of overhead if you want to collaborate on the same code :D
What do you think?

**Comment by ronag** [comment]
> What do you think?

Let's do it. Feel free to create a branch from this PR and close it.

**Pull request closed without merging**
