### PR TITLE
feat: add support for unix socket

### PR DESCRIPTION
**Pull request by ronag**
This is the least controversial solution I could come up with. Basically just do it like Node and curl already does.

For the host header it uses the passed hostname in the url. curl does the same.

### CODE REVIEW

**Comment by ronag** [comment]
@yoshuawuyts @szmarczak

**Comment by mcollina** [comment]
this might require some docs and maybe the tests should be skipped for Windows.

**Comment by ronag** [comment]
@yoshuawuyts would you mind taking a look at the docs?

**Comment by ronag** [comment]
@szmarczak @mcollina I might have jumped the gun here, should this live on the url or the options object?

i.e.

```js
new Client({
  ...url,
  socketPath
}, {
  socketTimeout: 1e3
})
```

vs


```js
new Client(url, {
  socketPath,
  socketTimeout: 1e3
})
```

**Comment by szmarczak** [comment]
I'm voting for the URL approach.

**Pull request merged**
