### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by ronag**
- Uses Node native HTTP parser. Improves performance and security. Removes dependency on `http-parser-js`.
- Added `headersTimeout` option.
- Fixed an assertion when using `client.pipeline` and the server does not consume the entire request body.
- Replace `client.full` with `client.busy` property.
- Improved support for legacy streams.
- Added support for IPC (e.g. unix sockets) through `socketPath` option.
- Refactoring and simplification.
- Throw not supported error for `CONNECT` method.

### CODE REVIEW

**Comment by ronag** [comment]
Also waiting for decision on https://github.com/mcollina/undici/pull/241 before release.

**Comment by ronag** [comment]
> Replace client.full with client.busy property.

Kind of makes this semver major. WDYT?

**Comment by ronag** [comment]
The switch to Node native parser has been a bit risky and I have found some misc bugs post the initial PR. But it feels pretty good now.

**Comment by mcollina** [comment]
Ok for me!

**Comment by ronag** [comment]
published

**Pull request closed without merging**
