### PR TITLE
pool stream + forward client opts

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
@szmarczak @mcollina the bench results I got are a bit suspiciously good... could you please also double check that I haven't made a mistake somewhere?

**Comment by szmarczak** [comment]
I'm getting

```
/home/szm/Desktop/undici/benchmarks/undici.js:30
      throw err
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writevGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:781:11)
    at Socket._writev (net.js:790:8)
    at doWrite (_stream_writable.js:376:12)
    at clearBuffer (_stream_writable.js:510:5)
    at Socket.Writable.uncork (_stream_writable.js:318:7)
    at endRequest (/home/szm/Desktop/undici/lib/client.js:259:19)
    at resume (/home/szm/Desktop/undici/lib/client.js:418:5)
    at endRequest (/home/szm/Desktop/undici/lib/client.js:262:3) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

on Node.js 14.2.0. I'll do the benchmarks using `benchmark.js`.

**Comment by szmarczak** [comment]
No luck either:

```
async_hooks.js:187
        ReflectApply(fn, thisArg, args);
        ^

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at Request.runInAsyncScope (async_hooks.js:187:9)
    at /home/szm/Desktop/undici/lib/request.js:145:20
    at internal/util.js:392:14
    at internal/streams/end-of-stream.js:170:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by ronag** [comment]
Can you send me your code?

**Comment by szmarczak** [comment]
Here you go: https://github.com/szmarczak/undici/blob/benchmarks/benchmark.js

**Comment by szmarczak** [comment]
Ah wait you're benchmarking http not https, my bad.

**Comment by szmarczak** [comment]
I got 42373 req/s.

**Comment by szmarczak** [comment]
I think I have to return a real stream, not an stream-like object, right?

**Comment by ronag** [comment]
Yes

**Comment by szmarczak** [comment]
Is there a way to disable `rejectUnauthorized` on a Pool instance?

**Comment by ronag** [comment]
Not at the moment. But it would be good to add.

**Comment by ronag** [comment]
Did you get both those errors with streamline?

**Comment by szmarczak** [comment]
Yep. But I switched to HTTP instead of HTTPS and used real streams and that fixed things for me. Benchmark.js reports this:

```
undici x 24,990 ops/sec ±1.48% (86 runs sampled)
```

**Comment by ronag** [comment]
Added tls/https forward options.

**Comment by ronag** [comment]
> Yep. But I switched to HTTP instead of HTTPS and used real streams and that fixed things for me. Benchmark.js reports this:

Can you make a PR with the benchmark code + results for core w agent keep alive?

**Comment by szmarczak** [comment]
> Can you make a PR with the benchmark code + results for core w agent keep alive?

Should I use Benchmark.js (`npm install benchmark`) or native?

**Comment by ronag** [comment]
> Should I use Benchmark.js (npm install benchmark) or native?

I'm fine with benchmark.js. @mcollina?

**Comment by ronag** [comment]
I'll remove the benchmark stuff form this PR.

**Pull request merged**
