### PR TITLE
fix: reset socket on GET & HEAD with body

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/mcollina/undici/issues/246

### CODE REVIEW

**Comment by ronag** [comment]
@mcollina How strongly do you feel in regards to "semversiness" on this?

**Comment by mcollina** [comment]
If we were crashing with GET and HEAD with a body before, it's a patch.

**Comment by ronag** [comment]
Added a "notes" section in the docs, documenting this.

**Comment by ronag** [comment]
@szmarczak

**Comment by szmarczak** [comment]
I suggest adding an option to disable this. At Got we had bunch of issues complaining about this behavior.

Otherwise looks good :)

**Comment by szmarczak** [comment]
I agree.

**Comment by ronag** [comment]
> Is this happening only if pipelining is higher than 1?

It happens the connection is re-used. Should probably clarify.

**Comment by ronag** [comment]
An alternative solution is to only send the request when nothing else is running, not send any further requests while it's running, and reconnect once the first response has been received.

**Comment by ronag** [comment]
@delvedor @mcollina @szmarczak PTAL. I think this might be a better solution.

**Comment by szmarczak** [comment]
Just a part of my comment from https://github.com/mcollina/undici/issues/258#issuecomment-658433206

> IMO, if it looks like a proper response, it should be parsed, and if the path doesn't match with the pipelined request (or there isn't any) then ~throw~ reconnect.

What about this?

**Comment by ronag** [comment]
> if the path doesn't match with the pipelined request 

I don't think responses contain the path?

**Comment by szmarczak** [comment]
If the data seems legit (looks like a HTTP/1.1 request), then you can check the path (`url`) here:

https://github.com/mcollina/undici/blob/e1990ce23c51a8b3fa4d4e18570f47467672ee28/lib/client-base.js#L370-L371

And if it doesn't match the pipelined request or there is none just simply reconnect.

**Comment by ronag** [comment]
> If the data seems legit (looks like a HTTP/1.1 request), then you can check the path (url) here:

url is only set for requests, not responses

**Comment by szmarczak** [comment]
Oooooh I was so confused for a while 😂 You're totally right. Pardon me.

**Pull request merged**
