### PR TITLE
feat: add opaque to request.stream

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/mcollina/undici/issues/140

### CODE REVIEW

**Comment by mcollina** [comment]
the docs is not clear on how to use this

**Comment by ronag** [comment]
> the docs is not clear on how to use this

I’m not sure how to make it more clear. Suggestion?

**Comment by mcollina** [comment]
what closure does this avoid?

**Comment by ronag** [comment]
Consider:

```js
function (req, res) {
   client.stream(opts, (data) => {
     proxy({ ...data, opaque: res })
   }
}
```

vs


```js
function (req, res) {
   client.stream({ ...opts, opaque: res }, proxy)
}
```

**Comment by mcollina** [comment]
Please add the example, so it’s clearer in the docs

**Comment by ronag** [comment]
Updated docs

**Pull request merged**
